import type React from "react";

export const styles: Record<string, React.CSSProperties> = {
  welcome: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100vh",
    gap: "1rem",
  },
  appContainer: {
    display: "flex",
    flexDirection: "column",
    height: "100vh",
  },
  topHeader: {
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    padding: "0.5rem 1rem",
    borderBottom: "1px solid #333",
    background: "#1a1a1a",
  },
  topHeaderTitle: {
    fontWeight: "bold",
    fontSize: "14px",
    color: "#888",
  },
  topHeaderSearch: {
    position: "relative",
    flex: 1,
    maxWidth: "400px",
    display: "flex",
    alignItems: "center",
    gap: "0.25rem",
  },
  topHeaderSearchInput: {
    flex: 1,
    padding: "0.5rem 0.75rem",
    background: "#2a2a2a",
    border: "1px solid #444",
    borderRadius: "4px",
    color: "#e0e0e0",
    fontSize: "14px",
    outline: "none",
  },
  searchDropdown: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    marginTop: "4px",
    background: "#2a2a2a",
    border: "1px solid #444",
    borderRadius: "4px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.3)",
    maxHeight: "300px",
    overflow: "auto",
    zIndex: 100,
  },
  searchDropdownItem: {
    padding: "0.5rem 0.75rem",
    cursor: "pointer",
    fontSize: "14px",
    color: "#e0e0e0",
  },
  topHeaderActions: {
    display: "flex",
    gap: "0.5rem",
  },
  topHeaderButton: {
    padding: "0.25rem 0.75rem",
    border: "1px solid #444",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
    color: "#e0e0e0",
  },
  mainContent: {
    display: "flex",
    flex: 1,
    overflow: "hidden",
  },
  sidebar: {
    width: "250px",
    borderRight: "1px solid #333",
    display: "flex",
    flexDirection: "column",
  },
  sidebarHeader: {
    padding: "1rem",
    borderBottom: "1px solid #333",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  newButton: {
    width: "24px",
    height: "24px",
    padding: 0,
    cursor: "pointer",
  },
  noteList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    flex: 1,
    overflow: "auto",
    outline: "none",
  },
  noteItem: {
    padding: "0.5rem 1rem",
    cursor: "pointer",
  },
  searchContainer: {
    padding: "0.5rem 1rem",
    borderBottom: "1px solid #333",
    display: "flex",
    gap: "0.5rem",
  },
  searchInput: {
    flex: 1,
    padding: "0.5rem",
    background: "#2a2a2a",
    border: "1px solid #444",
    borderRadius: "4px",
    color: "#e0e0e0",
    fontSize: "14px",
  },
  clearSearch: {
    background: "transparent",
    border: "none",
    color: "#888",
    fontSize: "18px",
    cursor: "pointer",
    padding: "0 0.25rem",
  },
  searchStatus: {
    padding: "0.5rem 1rem",
    color: "#666",
    fontStyle: "italic",
  },
  searchSnippet: {
    fontSize: "12px",
    color: "#888",
    marginTop: "0.25rem",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap" as const,
  },
  changeFolder: {
    margin: "1rem",
  },
  newNoteInput: {
    padding: "0.5rem 1rem",
    borderBottom: "1px solid #333",
  },
  input: {
    width: "100%",
    padding: "0.5rem",
    background: "#2a2a2a",
    border: "1px solid #444",
    borderRadius: "4px",
    color: "#e0e0e0",
    fontSize: "14px",
  },
  editor: {
    flex: 1,
    display: "flex",
    flexDirection: "column",
  },
  editorHeader: {
    padding: "1rem",
    borderBottom: "1px solid #333",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
  },
  editorActions: {
    display: "flex",
    gap: "0.5rem",
  },
  toggleButton: {
    fontSize: "12px",
    padding: "0.25rem 0.5rem",
  },
  viewModeToggle: {
    display: "flex",
    border: "1px solid #444",
    borderRadius: "4px",
    overflow: "hidden",
  },
  viewModeButton: {
    fontSize: "12px",
    padding: "0.25rem 0.5rem",
    border: "none",
    borderRadius: 0,
  },
  renderedView: {
    flex: 1,
    padding: "1rem",
    overflow: "auto",
    background: "#1a1a1a",
    color: "#e0e0e0",
    lineHeight: 1.6,
  },
  renderedP: {
    margin: "0 0 1rem 0",
  },
  wikiLink: {
    cursor: "pointer",
    textDecoration: "underline",
    textDecorationStyle: "dotted" as const,
  },
  textarea: {
    flex: 1,
    padding: "1rem",
    border: "none",
    resize: "none",
    fontFamily: "monospace",
    fontSize: "14px",
    background: "#1a1a1a",
    color: "#fff",
  },
  placeholder: {
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    color: "#666",
  },
  linksPanel: {
    width: "200px",
    borderLeft: "1px solid #333",
    display: "flex",
    flexDirection: "column",
  },
  linksPanelHeader: {
    padding: "1rem",
    borderBottom: "1px solid #333",
    fontWeight: "bold",
    fontSize: "12px",
    textTransform: "uppercase",
    color: "#888",
  },
  linksList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    overflow: "auto",
  },
  linkItem: {
    padding: "0.5rem 1rem",
    cursor: "pointer",
    fontSize: "14px",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
  },
  newBadge: {
    fontSize: "10px",
    background: "#444",
    padding: "2px 6px",
    borderRadius: "4px",
    color: "#888",
  },
  noteListContainer: {
    flex: 1,
    overflow: "auto",
  },
  sectionHeader: {
    padding: "0.5rem 1rem",
    fontSize: "11px",
    fontWeight: "bold",
    textTransform: "uppercase",
    color: "#666",
    borderBottom: "1px solid #333",
  },
  editableTitle: {
    cursor: "pointer",
  },
  renameTitleInput: {
    background: "#2a2a2a",
    border: "1px solid #6b9eff",
    borderRadius: "4px",
    color: "#e0e0e0",
    fontSize: "16px",
    padding: "0.25rem 0.5rem",
    outline: "none",
  },
  deleteButton: {
    background: "transparent",
    border: "none",
    cursor: "pointer",
    fontSize: "14px",
    padding: "0.25rem 0.5rem",
    opacity: 0.6,
  },
  contextMenu: {
    position: "fixed",
    background: "#2a2a2a",
    border: "1px solid #444",
    borderRadius: "4px",
    boxShadow: "0 2px 8px rgba(0, 0, 0, 0.3)",
    zIndex: 1000,
    minWidth: "120px",
  },
  contextMenuItem: {
    padding: "0.5rem 1rem",
    cursor: "pointer",
    fontSize: "14px",
  },
  modalOverlay: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    background: "rgba(0, 0, 0, 0.5)",
    display: "flex",
    alignItems: "flex-start",
    justifyContent: "center",
    paddingTop: "100px",
    zIndex: 1000,
  },
  commandPalette: {
    background: "#2a2a2a",
    border: "1px solid #444",
    borderRadius: "8px",
    width: "500px",
    maxWidth: "90vw",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.5)",
    overflow: "hidden",
  },
  commandInput: {
    width: "100%",
    padding: "1rem",
    background: "#2a2a2a",
    border: "none",
    borderBottom: "1px solid #444",
    color: "#e0e0e0",
    fontSize: "16px",
    outline: "none",
  },
  commandList: {
    maxHeight: "300px",
    overflow: "auto",
  },
  commandItem: {
    padding: "0.75rem 1rem",
    cursor: "pointer",
    fontSize: "14px",
    color: "#e0e0e0",
  },
  commandEmpty: {
    padding: "1rem",
    color: "#666",
    textAlign: "center",
    fontStyle: "italic",
  },
  graphContainer: {
    background: "#2a2a2a",
    border: "1px solid #444",
    borderRadius: "8px",
    boxShadow: "0 4px 20px rgba(0, 0, 0, 0.5)",
    overflow: "hidden",
  },
  graphHeader: {
    padding: "0.75rem 1rem",
    borderBottom: "1px solid #444",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "center",
    color: "#e0e0e0",
    fontWeight: "bold",
  },
  closeButton: {
    background: "transparent",
    border: "none",
    color: "#888",
    fontSize: "20px",
    cursor: "pointer",
    padding: "0 0.5rem",
  },
  rightPanel: {
    width: "300px",
    borderLeft: "1px solid #333",
    display: "flex",
    flexDirection: "column",
    background: "#1a1a1a",
    overflow: "hidden",
  },
  rightPanelSection: {
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
    flex: 1,
  },
  rightPanelSectionHeader: {
    padding: "0.5rem 1rem",
    borderBottom: "1px solid #333",
    fontSize: "12px",
    fontWeight: "bold",
    textTransform: "uppercase",
    color: "#888",
    background: "#222",
    cursor: "pointer",
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    userSelect: "none",
  },
  collapseIcon: {
    fontSize: "10px",
    width: "12px",
    color: "#666",
  },
  dragHandle: {
    cursor: "grab",
    color: "#555",
    fontSize: "10px",
    letterSpacing: "-2px",
    marginRight: "0.25rem",
  },
  dragOver: {
    background: "#333",
    borderTop: "2px solid #6b9eff",
  },
  dragging: {
    opacity: 0.5,
  },
  findBar: {
    display: "flex",
    alignItems: "center",
    gap: "0.5rem",
    padding: "0.5rem 1rem",
    background: "#252525",
    borderBottom: "1px solid #333",
  },
  findInput: {
    flex: 1,
    padding: "0.25rem 0.5rem",
    background: "#2a2a2a",
    border: "1px solid #444",
    borderRadius: "4px",
    color: "#e0e0e0",
    fontSize: "14px",
    outline: "none",
  },
  findCount: {
    fontSize: "12px",
    color: "#888",
    minWidth: "70px",
  },
  findButton: {
    background: "#333",
    border: "1px solid #444",
    borderRadius: "4px",
    color: "#e0e0e0",
    cursor: "pointer",
    padding: "0.25rem 0.5rem",
    fontSize: "14px",
  },
  textareaContainer: {
    flex: 1,
    position: "relative",
    display: "flex",
    flexDirection: "column",
  },
  autocompleteDropdown: {
    position: "absolute",
    top: "60px",
    left: "1rem",
    background: "#2a2a2a",
    border: "1px solid #444",
    borderRadius: "4px",
    boxShadow: "0 4px 12px rgba(0, 0, 0, 0.3)",
    maxHeight: "200px",
    overflow: "auto",
    zIndex: 100,
    minWidth: "200px",
  },
  autocompleteItem: {
    padding: "0.5rem 0.75rem",
    cursor: "pointer",
    fontSize: "14px",
    color: "#e0e0e0",
  },
  rightPanelSectionContent: {
    overflow: "auto",
    flex: 1,
  },
  rightPanelGraphContainer: {
    flex: 1,
    minHeight: "200px",
    display: "flex",
  },
  rightPanelEmpty: {
    padding: "1rem",
    color: "#666",
    textAlign: "center",
    fontStyle: "italic",
  },
};
